version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"  # Changed host port to 3001
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite_data:/app/data
    command: npm run dev

volumes:
  sqlite_data: