name: Express AI Powered app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Apply database migrations
        run: npx prisma migrate deploy

      - name: Check code formatting
        run: yarn format:check

      - name: Run ESLint
        run: yarn lint

      - name: Run tests
        run: yarn test
        env:
          DATABASE_URL: 'file:./test.db'

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: test-pipeline-express:test

      - name: Test Docker container
        run: |
          docker run -d -p 3001:3000 test-pipeline-express:test
          echo "Waiting for application to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3001/users; then
              echo "Application is up!"
              break
            fi
            echo "Attempt $i: Application not ready yet..."
            sleep 2
            if [ $i -eq 30 ]; then
              echo "Application failed to start"
              exit 1
            fi
          done
          docker ps -q | xargs -r docker stop
